language: python
python:
  - "3.4"
  - "3.3"
  - "2.7"
install:
  - pip install -r requirements.txt
  - pip install coverage
  - pip install coveralls
script: nosetests --with-coverage --cover-tests --cover-package=app
after_success:
  coveralls
